name: Show Me the S3cr3tz
on: 
 workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      run: |
       ./test.ps1
